### ISSUE TITLE
hi, 

### ISSUE THREAD

**Issue by mastadev72** [baudom/easytank#66]
Sorry i use this way.
But i ran into your easytank. and wouwwww that looks good.
i studied a bity and i saw you are collecting stats from the app to umami.

I tried to get it working on a testapp, but im beginner, but i really like to understand how it works.

i hope u can help me
webheads@gmail.com

**Comment by baudom** [comment]
hey, first of all - thanks, happy to hear :)

**Comment by baudom** [comment]
hey, 
first of all, thanks - happy to hear :)

yes, some clicks and view impressions are (if the user agrees to) tracked and collected to a private umami instance.

Could you maybe describe your problem or what problem you're running into? May have a look at my implementation in #50 or visit the umami docs: https://umami.is/docs

Since this is not really a "issue" of this repository, I would close this Issue.

**Comment by mastadev72** [comment]
Thanks man, i will have a look, keep up the good work, it looks really promosing. :)
